### ISSUE TITLE
Do Project Setup

### ISSUE THREAD

**Issue by myself112** [myself112/mern-stack#1]
- [x] crate react.js app
- [x]  create backend server with express.js
- [x] update global README.md file
- [x] separate folders for frontend and backend
- [x] Install Tailwind css

**Comment by razak571** [comment]
Hi, I am willing to contribute to issue #1

**Comment by myself112** [comment]
> Hi, I am willing to contribute to issue #1

Sure, fork the repo, work on tasks, and raise the PR. I will review and merge if it meets the requirements.

**Comment by razak571** [comment]
> > Hi, I am willing to contribute to issue #1
> 
> Sure, fork the repo, work on tasks, and raise the PR. I will review and merge if it meets the requirements.

Thanks...! I will.

**Comment by myself112** [comment]
This is I am closing. Thanks for the contribution. @razak571
